name: ManhuntPlugin
version: '${project.version}'
main: newamazingpvp.manhuntplugin.ManhuntPlugin
api-version: '1.21'
folia-supported: true
commands:
    manhunt:
        description: Manhunt command
        usage: /manhunt <help>
        aliases: [mh]
